export const Colors = {
    primary: '#35495e',
    secondary: '#42b883',
    white: '#fff',
    black: '#000',
    lightGray: '#838456',
    accent: '#ffc231',
    accentRed: '#f85d2e',
    accentPink: '#f96165'
}

export const dummieData = {
  "pizzas": [{
    id: 1,
    isTopOfTheWeek: false,
    category: 'Plain Cheese Pizza',
    price: 280,
    crust: 'Thick Crust',
    name: 'Pizza 1',
    image: require('../img/pizzaOne.jpg'),
    duration: '30 min',
    serving: 1,
    size: 'large',
    ratings: '5.0',
    recipe: 'I top convenient refrigerated pizza dough with leftover taco meat, tomatoes and cheese, bringing a full-flavored fiesta to the table in under half an hour. —Sarah Vovos, Middleton, Wisconsin.',
    details: 'pie, dish made by lining a shallow container with pastry and filling the container with a sweet or savoury mixture. A top crust may be added; the pie is baked until the crust is crisp and the filling is cooked through',
  },
{
    id: 2,
    isTopOfTheWeek: true,
    category: 'PizzaTwo',
    price: 250,
    crust: 'Thick Crust',
    name: 'Pizza 2',
    image: require('../img/pizzaTwo.jpeg'),
    duration: '20 min',
    serving: 10,
    size: 'Medium',
    ratings: '5.0',
    recipe: '2 bacon strips, beef tenderloin steaks (5 ounces each), cups sliced baby portobello mushrooms, teaspoon dried thyme',
    details: 'Italy has many variations of pizza. The Neapolitan pizza, or Naples-style pizza, is made specifically with buffalo mozzarella (produced from the milk of Italian Mediterranean buffalo) or fior di latte (mozzarella produced from the milk of prized Agerolese cows) and with San Marzano tomatoes or pomodorino vesuviano (a variety of grape tomato grown in Naples). Roman pizza often omits tomatoes (an early 16th-century import) and uses onions and olives',
  },
{
    id: 3,
    isTopOfTheWeek: false,
    category: 'PizzaThree',
    price: 80,
    crust: 'Thin Crust',
    name: 'Pizza 3',
    image: require('../img/pizzaThree.webp'),
    duration: '15 min',
    serving: 5,
    size: 'large',
    ratings: '5.0',
    recipe: '2 bacon strips, beef tenderloin steaks (5 ounces each), cups sliced baby portobello mushrooms, teaspoon dried thyme',
    details: 'The popularity of pizza in the United States began with the Italian community in New York City, where the Neapolitan pizza had an early influence. The first pizzeria appeared in New York City about the turn of the 20th century. After World War II the pizza industry boomed. Soon there was scarcely a hamlet without a pizzeria',
  },
{
    id: 4,
    isTopOfTheWeek: false,
    category: 'Biggie Cheese',
    price: 280,
    crust: 'Thick Crust',
    name: 'Pizza 4',
    image: require('../img/pizzaFour.jpg'),
    duration: '1 hour',
    serving: 3,
    size: 'large 18',
    ratings: '5.0',
    recipe: '2 bacon strips, beef tenderloin steaks (5 ounces each), cups sliced baby portobello mushrooms, teaspoon dried thyme',
    details: '',  
},
{
    id: 5,
    isTopOfTheWeek: true,
    category: 'PizzaFive',
    price: 280,
    crust: 'Thick Crust',
    name: 'Mexican Green Wave',
    image: require('../img/pizzaFive.jpeg'),
    duration: '5 min',
    serving: 2,
    size: 'large',
    ratings: '5.0',
    recipe: '2 bacon strips, beef tenderloin steaks (5 ounces each), cups sliced baby portobello mushrooms, teaspoon dried thyme',
    details: 'shepherd’s pie, common and inexpensive British dish originating from the sheep country in Scotland and northern England. It is a baked meat pie made with minced or diced lamb and topped with a thick layer of mashed potatoes. Although the dish is sometimes called cottage pie,',
  }],
'softDrinks':[
    {
      id: 1,
      image: require('../img/coke.png'),
      name: 'Coca Cola',
      price: '20',
      rating: '5.0',
      isTopOfTheWeek: true,
      size: 'Medium Glass',
      crust: "Small Ice"
    },
    {
      id: 2,
      image: require('../img/orange.jpg'),
      name: 'Orange Juice',
      price: '15',
      rating: '5.0',
      isTopOfTheWeek: true,
      size: 'Medium Glass',
      crust: "Small Ice"
    },
    {
      id: 3,
      image: require('../img/mango.jpg'),
      name: 'Mango Juice',
      price: '25',
      rating: '5.0',
      isTopOfTheWeek: false,
      size: 'Medium Glass',
      crust: "Large Ice"
    },
    {
      id: 4,
      image: require('../img/guava.jpeg'),
      name: 'Guava Juice',
      price: '25',
      rating: '5.0',
      isTopOfTheWeek: false,
      size: 'Medium Glass',
      crust: "Large Ice"
    },
    {
      id: 5,
      image: require('../img/sprite.png'),
      name: 'Sprite',
      price: '25',
      rating: '5.0',
      isTopOfTheWeek: false,
      size: 'Medium Glass',
      crust: "Large Ice"
    },
    {
      id: 6,
      image: require('../img/brew.jpg'),
      name: 'Iron Brew',
      price: '25',
      rating: '5.0',
      isTopOfTheWeek: false,
      size: 'Medium Glass',
      crust: "Large Ice"
    },
]
}